parameters:
  mailer.gmail_user: 'issa@gmail.com'
  mailer.gmail_password: '123456'
  firstName: "Issa"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $firstName: "%firstName%"

  _instanceof:
    App\HasLoggerInterface:
      tags: ['with_logger']


  order_controller:
    class: App\Controller\OrderController
    public: true
    calls:
      - method: sayHello
        arguments: ['Bonjour à tous']
    
  
  texter.sms:
    class: App\Texter\SmsTexter
    arguments: ['service.sms.com', 'apikey1234']

  App\Controller\OrderController:
    alias: order_controller
    public: true
  App\Database\Database: '@database'
  App\Logger: '@logger'
  App\Mailer\GmailMailer: '@mailer.gmail'
  App\Mailer\SmtpMailer: '@mailer.gmail'
  App\Mailer\MailerInterface: '@mailer.gmail'
  App\Texter\SmsTexter: '@texter.sms'
  App\Texter\FaxTexter: '@texter.sms'
  App\Texter\TexterInterface: '@texter.sms'


  
 