parameters:
  mailer.gmail_user: 'issa@gmail.com'
  mailer.gmail_password: '123456'
  firstName: "Issa"

services:
  _instanceof:
    App\HasLoggerInterface:
      tags: ['with_logger']

  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $firstName: "%firstName%"

  App\:
    resource: '../src/*'
    exclude: '../src/{Dependencyinjection}'

  App\Controller\OrderController:
    public: true
    calls:
      - method: sayHello
        arguments: ['Bonjour à tous']

  App\Mailer\MailerInterface:
    alias: App\Mailer\GmailMailer

  App\Texter\TexterInterface:
    alias: App\Texter\SmsTexter

  App\Mailer\GmailMailer:
    arguments:
      - '%mailer.gmail_user%'
      - '%mailer.gmail_password%'

  App\Texter\SmsTexter:
    arguments: ['service.sms.com', 'apikey1234']
  
  

  
 